# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tracked_model.control


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_num', models.IntegerField()),
                ('some_txt', models.TextField()),
                ('some_date', models.DateField(null=True)),
            ],
            bases=(tracked_model.control.TrackedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FKModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_ip', models.GenericIPAddressField()),
                ('basic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.BasicModel')),
            ],
            bases=(tracked_model.control.TrackedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='M2MModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bunch', models.ManyToManyField(to='testapp.BasicModel')),
            ],
            bases=(tracked_model.control.TrackedModelMixin, models.Model),
        ),
    ]
