# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicmodel',
            name='some_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
